name: Download Chess960 Games

on:
  workflow_dispatch:

jobs:
  fetch-games:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Run Chess960 Downloader
      run: |
        python 960.py

    - name: Upload PGN files
      uses: actions/upload-artifact@v4
      with:
        name: chess960-games
        path: "*.pgn"
