name: Download Chess960 Games

on:
  workflow_dispatch:

jobs:
  fetch-games:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Run Chess960 Downloader
      run: |
        python -u 960.py

    - name: Commit PGNs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.pgn
        git commit -m "Update PGNs from Lichess bots" || echo "No changes to commit"
        git push
